<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<title>商户管理</title>
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<link rel="stylesheet" href="/static/css/font.css">
	<link rel="stylesheet" href="/static/css/style.css">

</head>

<body>
<div class="x-nav">
        <span class="layui-breadcrumb">
            <a href="javascript:;">首页</a> <a><cite>商户列表</cite></a>
        </span>
    <!-- function btn -->
	<a class="layui-btn layui-btn-sm x-nav-btn" href="javascript:location.replace(location.href);" title="刷新">
		<i class="layui-icon layui-icon-refresh"></i>
	</a>
	<button class="layui-btn layui-btn-sm x-nav-btn" onclick="xShow('添加商户','/merchant/edit')">
		<i class="layui-icon">&#xe61f;</i>添加商户
	</button>
</div>
<div class="x-body">
	<!-- sreach -->
	<form class="layui-form we-search" method="POST">
		<div class="layui-input-inline btn-dropdown">
			<select clasee="" id="condition"">
			<option value="tx_no">商户ID</option>
			<option value="tx_out_no">商户名</option>
			<option value="uid">代理ID</option>
            </select>
            <input type="text" name="tx_no" lay-verify="title" autocomplete="off" placeholder="请输入" class="layui-input">
		</div>
		<div class="layui-input-inline w100px">
			<select name="chan_name">
				<option value="">网关名</option>
				<option value="010">连连支付_网银哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈</option>
				<option value="021">畅捷支付_快捷</option>
				<option value="021">畅捷支付_快捷</option>
				<option value="021">畅捷支付_快捷</option>
			</select>
		</div>
		<div class="layui-input-inline w100px">
			<select name="state">
				<option value="">商户状态</option>
				<option value="0">关闭</option>
				<option value="1">开启</option>
				<option value="2">全部</option>
			</select>
		</div>
		<div class="layui-input-inline">
			<button class="layui-btn" lay-submit lay-filter="searchForm"><i class="layui-icon">&#xe615;</i></button>
		</div>
	</form>
    <!-- table -->
	<table id="tableList" class="layui-hide" lay-filter="chanList"></table>
	<script type="text/html" id="buttonTpl">
		{{#  if(d.state == 1){ }}
		<span class="layui-badge layui-bg-green"> 开启 </span>
        {{#  } else { }}
		<span class="layui-badge layui-bg-red"> 关闭 </span>
        {{#  } }}
	</script>
	<script type="text/html" id="barDemo">
		<a title="查看" lay-event="edit" href="javascript:;"> <i class="layui-icon layui-icon-search"></i> </a>
		<a title="编辑" lay-event="edit" href="javascript:;"> <i class="layui-icon layui-icon-edit"></i> </a>
		<a title="资金" lay-event="edit" href="javascript:;"> <i class="layui-icon layui-icon-dollar"></i> </a>
		<a title="删除" lay-event="del" href="javascript:;"> <i class="layui-icon layui-icon-delete"></i> </a>
	</script>
</div>
<script src="/static/layui/layui.js"></script>
<script src="/static/js/admin.js"></script>
<script>
    layui.use(['table', 'jquery', 'form', 'layer', 'element'], function () {
        var table   = layui.table,
            $       = layui.jquery,
            form    = layui.form,
            element = layui.element,
            layer   = layui.layer
        //渲染table
        renderTable(null)

        /* table function */
        function renderTable (dateField) {
            table.render({
                elem        : '#tableList',
                method      : 'post',
                url         : '/merchant/list',
                where       : dateField,
                // 分页
                // page:   true,
                page        : { //支持传入 laypage 组件的所有参数（某些参数除外，如：jump/elem） - 详见文档
                    layout: ['limit', 'count', 'prev', 'page', 'next', 'skip'], //自定义分页布局
                    groups: 1, //只显示 1 个连续页码
                    first : false, //不显示首页
                    last  : false, //不显示尾页
                },
                limits      : [25, 50, 100],
                limit       : 25, //每页默认显示的数量
                cellMinWidth: 80,
                cols        : [
                    [ //表头
                        { field: 'uid', title: '商户ID', minWidth: 90, align: 'center', sort: true }
                        , { field: 'username', title: '商户名', minWidth: 100, align: 'center' }
                        , { field: 'email', title: '邮箱', minWidth: 180, align: 'center' }
                        , { field: 'phone', title: '手机号', minWidth: 120, align: 'center' }
                        , { field: 'qq', title: 'QQ', minWidth: 120, align: 'center' }
                        , { field: 'balance', title: '余额', minWidth: 120, align: 'center' }
                        , { field: 'frozen', title: '冻结', minWidth: 120, align: 'center' }
                        , { field: 'fixed', title: '保证金', minWidth: 120, align: 'center' }
                        , { field: 'state', title: '状态', templet: '#buttonTpl', minWidth: 90, align: 'center' }
                        , { field: 's_uid', title: '上1级ID', minWidth: 80, align: 'center' }
                        , { field: 'ss_uid', title: '上2级ID', minWidth: 80, align: 'center' }
                        , { field: 'sss_uid', title: '上3级ID', minWidth: 80, align: 'center' }
                        , { field: 'adm_id', title: '业务员ID', minWidth: 80, align: 'center' }
                        , { field: 'ctime', title: '注册时间', minWidth: 100, align: 'center' }
                        , { field: 'memo', title: '备注', minWidth: 100, align: 'center' }
                        , { title: '操作', toolbar: '#barDemo', width: 110, align: 'center' },
                    ],
                ],
            })
        }

        /* 搜索 */
        form.on('submit(searchForm)', function (data) {
            layer.msg(JSON.stringify(data.field))
            renderTable(data.field)
            return false
        })

        /* 监听table行工具事件 */
        table.on('tool(chanList)', function (obj, index) {
            let data = obj.data
            if (obj.event === 'del') {
                layer.confirm('确定删除该通道?', function (index) {
                    $.ajax({
                        type    : 'get',
                        url     : 'https://a.jdpay.com/channel/chanDel/' + data.chan_id,
                        dataType: 'json',
                        success : function (res) {
                            if (res.code === 0) {
                                layer.msg(res.msg, { icon: 1, time: 1000 }, function () {
                                    obj.del()
                                })
                            } else {
                                layer.msg(res.msg, { icon: 2 })
                            }
                        },
                        error   : function (err) {
                            console.log(err)
                            // if (err.responseJSON.code) {
                            //     layer.msg(err.responseJSON.msg, {icon: 2});
                            // } else {
                            //     layer.msg('未知错误', {icon: 5});
                            // }
                        },
                    })
                    layer.close(index)
                })
            }
            // 存储行数据
            if (obj.event === 'edit') {
                sessionStorage.setItem('user_detail', JSON.stringify(data))
                xShow('用户信息', '/merchant/edit/'+data.uid)
            }

            // 存储行数据
            if (obj.event === 'rate') {
                sessionStorage.setItem('edit_chan', JSON.stringify(data))
                xShow('网关费率', '/merchant/rate/'+data.uid)
            }

        })
    })
</script>
</body>

</html>