<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>用户编辑</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/static/css/font.css">
    <!--<link rel="stylesheet" href="/static/layui/css/layui.css">-->
    <link rel="stylesheet" href="/static/css/style.css">

</head>

<body>

<table class="layui-hide" id="test"></table>


<script src="/static/layui/layui.js"></script>
<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->

<script>
layui.use('table', function(){
    var table = layui.table;

    table.render({
        elem: '#test'
        ,url:'/merchant/list'
        ,cellMinWidth: 80 //全局定义常规单元格的最小宽度，layui 2.2.1 新增
        ,method:'POST'
        ,cols: [[
            {field:'uid', title: 'ID', sort: true}
            ,{field:'username', title: '用户名'} //width 支持：数字、百分比和不填写。你还可以通过 minWidth 参数局部定义当前单元格的最小宽度，layui 2.2.1 新增
            ,{field:'email', title: '性别', sort: true}
            ,{field:'phone', title: '手机'}
            ,{field:'memo', title: '备注', sort: true, align: 'right'}
        ]]
    });
});
</script>
</body>
</html>