<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>管理登录</title>
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<!-- 顶部开始 -->
<div class="container layui-bg-cyan">
    <div class="logo"> <a _href="/index/welcome" lay-title="<i class='layui-icon layui-icon-home'></i>">XPay</a> </div>
    <div class="left_open"> <i title="展开左侧栏" class="iconfont">&#xe699;</i> </div>

    <ul class="layui-nav left fast-add" lay-filter="">
        <li class="layui-nav-item">
            <a href="javascript:;">+新增</a>
            <dl class="layui-nav-child">
                <!-- 二级菜单 -->
                <dd> <a onclick="xShow('商户','https://www.youfa365.com/')"><i class="iconfont">&#xe6b8;</i>商户</a> </dd>
                <dd> <a onclick="xShow('代理','https://www.youfa365.com/')"><i class="iconfont">&#xe6a2;</i>代理</a> </dd>
            </dl>
        </li>
    </ul>

    <ul class="layui-nav right">
        <li class="layui-nav-item"> <a href="#"><i class="layui-icon layui-icon-delete"></i><cite class="layui-hide-xs">清除缓存</cite></a> </li>
        <li class="layui-nav-item to-index layui-hide-xs"> <a href="https://www.layui.com/admin/std/dist/views/" target="_blank">前台首页</a> </li>
        <li class="layui-nav-item">
            <a href="javascript:;"><i class="layui-icon layui-icon-friends"></i></a>
            <dl class="layui-nav-child r0">
                <!-- 二级菜单 -->
                <dd> <a onclick="xShow('切换帐号','/sign/out')">切换帐号</a> </dd>
                <dd> <a onclick="xShow('修改密码','/account/psw')">修改密码</a> </dd>
                <dd> <a class="loginout" href="sign/out">退出</a> </dd>
            </dl>
        </li>
    </ul>
</div>
<!-- 顶部结束 -->

<!-- 中部开始 -->

<!-- 左侧菜单开始 -->
<div class="left-nav">
    <div id="side-nav">
        <ul id="nav">
            <li>
                <a href="javascript:;"> <i class="layui-icon layui-icon-senior"></i> <cite>交易管理</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/tx/paying"> <i class="iconfont">&#xe6a7;</i> <cite>充值中订单</cite> </a> </li>
                    <li> <a _href="/tx/paid"> <i class="iconfont">&#xe6a7;</i> <cite>充值历史订单</cite> </a> </li>
                    <li> <a _href="/tx/remit"> <i class="iconfont">&#xe6a7;</i> <cite>代付订单</cite> </a> </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"> <i class="layui-icon layui-icon-user"></i> <cite>商户管理</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/merchant/list"> <i class="iconfont">&#xe6a7;</i> <cite>商户列表</cite> </a> </li>
                    <li> <a _href="/static/pages/trader/balance-edit-record.html"> <i class="iconfont">&#xe6a7;</i> <cite>余额记录</cite> </a> </li>
                    <li> <a _href="/static/pages/trader/ip-record.html"> <i class="iconfont">&#xe6a7;</i> <cite>登入记录</cite> </a> </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="layui-icon layui-icon-group"></i> <cite>代理管理</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/static/pages/agent/agent-list.html"> <i class="iconfont">&#xe6a7;</i> <cite>代理列表</cite> </a> </li>
                    <li> <a _href="/static/pages/agent/agent-remit-list.html"> <i class="iconfont">&#xe6a7;</i> <cite>代理代付列表</cite> </a> </li>
                    <li> <a _href="/static/pages/agent/agent-monthly-profit.html"> <i class="iconfont">&#xe6a7;</i> <cite>代理利润</cite> </a> </li>
                    <li> <a _href="/static/pages/agent/agent-log-balance.html"> <i class="iconfont">&#xe6a7;</i> <cite>余额记录</cite> </a> </li>
                    <li> <a _href="/static/pages/agent/agent-log-balance.html"> <i class="iconfont">&#xe6a7;</i> <cite>登入记录</cite> </a> </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"> <i class="iconfont">&#9820;</i> <cite>公告管理</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/static/pages/gateway-channel/list-account.html"> <i class="iconfont">&#xe6a7;</i> <cite>新公告</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-pack.html"> <i class="iconfont">&#xe6a7;</i> <cite>公告列表</cite> </a> </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"> <i class="iconfont">&#9820;</i> <cite>通道管理</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/static/pages/gateway-channel/list-account.html"> <i class="iconfont">&#xe6a7;</i> <cite>通道列表</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-pack.html"> <i class="iconfont">&#xe6a7;</i> <cite>通道组列表</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-channel.html"> <i class="iconfont">&#9822;</i> <cite>网关列表</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-product.html"> <i class="iconfont">&#9812;</i> <cite>支付产品列表</cite> </a> </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"> <i class="iconfont">&#9820;</i> <cite>统计信息</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/static/pages/gateway-channel/list-account.html"> <i class="iconfont">&#xe6a7;</i> <cite>平台报表</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-account.html"> <i class="iconfont">&#xe6a7;</i> <cite>业务员统计</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-account.html"> <i class="iconfont">&#xe6a7;</i> <cite>商户报表</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-pack.html"> <i class="iconfont">&#xe6a7;</i> <cite>代理报表</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-product.html"> <i class="iconfont">&#9812;</i> <cite>支付产品列表</cite> </a> </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"> <i class="iconfont">&#9820;</i> <cite>财务管理</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/static/pages/gateway-channel/list-account.html"> <i class="iconfont">&#xe6a7;</i> <cite>通道列表</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-pack.html"> <i class="iconfont">&#xe6a7;</i> <cite>通道组列表</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-channel.html"> <i class="iconfont">&#9822;</i> <cite>网关列表</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-product.html"> <i class="iconfont">&#9812;</i> <cite>支付产品列表</cite> </a> </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"> <i class="layui-icon layui-icon-username"></i> <cite>后台用户</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/static/pages/gateway-channel/list-account.html"> <i class="iconfont">&#xe6a7;</i> <cite>用户列表</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-pack.html"> <i class="iconfont">&#xe6a7;</i> <cite>角色管理</cite> </a> </li>
                    <li> <a _href="/static/pages/gateway-channel/list-channel.html"> <i class="iconfont">&#9822;</i> <cite>权限管理</cite> </a> </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"> <i class="iconfont">&#9813;</i> <cite>系统设置</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/static/pages/settings/setting-basic.html"> <i class="iconfont">&#xe6a7;</i> <cite>基本设置</cite> </a> </li>
                    <li> <a _href="/static/pages/settings/setting-email.html"> <i class="iconfont">&#xe6a7;</i> <cite>邮件设置</cite> </a> </li>
                    <li> <a _href="/static/pages/settings/setting-message.html"> <i class="iconfont">&#xe6a7;</i> <cite>短信设置</cite> </a> </li>
                    <li> <a _href="/static/pages/settings/setting-planned.html"> <i class="iconfont">&#xe6a7;</i> <cite>计划任务</cite> </a> </li>
                    <li> <a _href="/static/pages/settings/setting-phone.html"> <i class="iconfont">&#xe6a7;</i> <cite>手机设置</cite> </a> </li>
                    <li> <a _href="/static/pages/settings/cleansing-data.html"> <i class="iconfont">&#xe6a7;</i> <cite>数据清理</cite> </a> </li>
                    <li> <a _href="/static/pages/settings/setting-pwd.html"> <i class="iconfont">&#xe6a7;</i> <cite>修改密码</cite> </a> </li>
                    <li> <a _href="/static/pages/settings/setting-blacklist.html"> <i class="iconfont">&#xe6a7;</i> <cite>黑名单管理</cite> </a> </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<!-- 左侧菜单结束 -->

<!-- 右侧主体开始 -->
<div class="page-content">
    <div class="layui-tab tab" lay-filter="wenav_tab" id="WeTabTip" lay-allowclose="true">
        <ul class="layui-tab-title" id="tabName">
            <li lay-id="1"><i class="layui-icon layui-icon-home"></i></li>
        </ul>
        <div class="layui-tab-content">
            <div class="layui-tab-item layui-show">
                <iframe src="/index/welcome" frameborder="0" scrolling="yes" class="xframe"></iframe>
            </div>
        </div>
    </div>
</div>
<!-- 辅助元素，一般用于移动设备下遮罩 -->
<div class="page-content-bg"></div>

<!-- 右侧主体结束 -->
<!-- 中部结束 -->

<!--Tab菜单右键弹出菜单-->
<ul class="rightMenu" id="rightMenu">
    <li data-type="fresh">刷新</li>
    <li data-type="current">关闭当前</li>
    <li data-type="other">关闭其它</li>
    <li data-type="all">关闭所有</li>
</ul>

<script src="/static/layui/layui.js"></script>
<script src="/static/js/admin.js"></script>
<script type="text/javascript">

    // layui扩展模块的两种加载方式-示例
    // layui.extend({
    //   admin: '{/}./static/js/admin' // {/}的意思即代表采用自有路径，即不跟随 base 路径
    // });
    // //使用拓展模块
    // layui.use('admin', function(){
    //   var admin = layui.admin;
    // });

    layui.config({
        base: './static/js/',
        version: '101100'
    });
    layui.use(['jquery'], function(){
        const $ = layui.jquery;
        // 模拟登录路由拦截
        $(function(){
            let login = JSON.parse(sessionStorage.getItem("login"));
            if(login == 0){
                window.location.href='/sign/in';
            }
            return false;
        })
    });
</script>
</body>
</html>