<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
	<title>代理后台</title>
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="/css/font.css">
    <link rel="stylesheet" href="/css/style.css">
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<!-- 顶部开始 -->
<div class="container layui-bg-cyan">
    <div class="logo"> <a _href="./pages/welcome.html" lay-title="<i class='layui-icon layui-icon-home'></i>">XPay</a> </div>
    <div class="left_open"> <i title="展开左侧栏" class="iconfont">&#xe699;</i> </div>

    <ul class="layui-nav left fast-add" lay-filter="">
        <li class="layui-nav-item">
            <a href="javascript:;">+ 新增</a>
            <dl class="layui-nav-child">
                <!-- 二级菜单 -->
                <dd> <a onclick="xShow('新增商户','https://www.youfa365.com/')"><i class="iconfont">&#xe6b8;</i>商户</a> </dd>
                <dd> <a onclick="xShow('新增下级代理','https://www.youfa365.com/')"><i class="layui-icon layui-icon-friends"></i>代理</a> </dd>
            </dl>
        </li>
    </ul>

    <ul class="layui-nav right" lay-filter="">
        <li class="layui-nav-item">
            <a href="javascript:;"><i class="layui-icon layui-icon-friends"></i></a>
            <dl class="layui-nav-child r0">
                <!-- 二级菜单 -->
                <dd> <a onclick="xShow('切换帐号','/sign/out')"><i class="layui-icon layui-icon-username"></i>账户信息</a> </dd>
                <dd> <a onclick="xShow('修改密码','/account/psw')"><i class="layui-icon layui-icon-password"></i>密码更改</a> </dd>
                <dd> <a onclick="xShow('修改密码','/account/psw')"><i class="layui-icon layui-icon-release"></i>邮箱更改</a> </dd>
                <dd> <a class="loginout" href="/sign/out"><i class="layui-icon layui-icon-close"></i>注销</a></dd>
            </dl>
        </li>
    </ul>
</div>
<!-- 顶部结束 -->

<!-- 中部开始 -->

<!-- 左侧菜单开始 -->
<div class="left-nav">
    <div id="side-nav">
        <!--代理部分-->
        <ul id="nav">
            <li>
                <a href="javascript:;"> <i class="layui-icon layui-icon-senior"></i> <cite>交易管理</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/recharge"> <i class="iconfont">&#xe6a7;</i> <cite>入款订单</cite> </a> </li>
                    <li> <a _href="./pages/transaction/remit.html"> <i class="iconfont">&#xe6a7;</i> <cite>代付订单</cite> </a> </li>
                    <li> <a _href="./pages/transaction/remit.html"> <i class="iconfont">&#xe6a7;</i> <cite>冻结订单</cite> </a> </li>
                    <li> <a _href="./pages/transaction/remit.html"> <i class="iconfont">&#xe6a7;</i> <cite>退款订单</cite> </a> </li>
                </ul>
            </li>
            <li> <a _href="/recharge"> <i class="layui-icon layui-icon-user"></i> <cite>商户列表</cite> </a> </li>
            <li>
                <a href="javascript:;"> <i class="layui-icon layui-icon-dollar"></i> <cite>财务管理</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/merchant/list"> <i class="iconfont">&#xe6a7;</i> <cite>账户资金</cite> </a> </li>
                    <li> <a _href="./pages/trader/balance-list.html"> <i class="iconfont">&#xe6a7;</i> <cite>代付出款</cite> </a> </li>
                    <li> <a _href="./pages/trader/balance-day-list.html"> <i class="iconfont">&#xe6a7;</i> <cite>商户每日余额列表</cite> </a> </li>
                    <li> <a _href="./pages/trader/ip-record.html"> <i class="iconfont">&#xe6a7;</i> <cite>资金流水</cite> </a> </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"> <i class="layui-icon layui-icon-username"></i> <cite>账户管理</cite> <i class="iconfont nav_right">&#xe697;</i> </a>
                <ul class="sub-menu">
                    <li> <a _href="/recharge"> <i class="iconfont">&#xe6a7;</i> <cite>修改密码</cite> </a> </li>
                    <li> <a _href="./pages/transaction/remit.html"> <i class="iconfont">&#xe6a7;</i> <cite>账户信息</cite> </a> </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<!-- 左侧菜单结束 -->

<!-- 右侧主体开始 -->
<div class="page-content">
    <div class="layui-tab tab" lay-filter="wenav_tab" id="WeTabTip" lay-allowclose="true">
        <ul class="layui-tab-title" id="tabName">
            <li lay-id="1"><i class="layui-icon layui-icon-home"></i></li>
        </ul>
        <div class="layui-tab-content">
            <div class="layui-tab-item layui-show">
                <iframe src='index/welcome' frameborder="0" scrolling="yes" class="xframe"></iframe>
            </div>
        </div>
    </div>
</div>
<!-- 辅助元素，一般用于移动设备下遮罩 -->
<div class="page-content-bg"></div>

<!-- 右侧主体结束 -->
<!-- 中部结束 -->


<!-- 底部开始 -->
<div class="footer">
    <div class="copyright">©2018 支付</div>
</div>
<!-- 底部结束 -->

<!--Tab菜单右键弹出菜单-->
<ul class="rightMenu" id="rightMenu">
    <li data-type="fresh">刷新</li>
    <li data-type="current">关闭当前</li>
    <li data-type="other">关闭其它</li>
    <li data-type="all">关闭所有</li>
</ul>

<script type="text/javascript" src="./layui/layui.js" charset="utf-8"></script>
<script type="text/javascript">
    layui.config({
        base: './js/'
        //,version: '101100'
    }).use('admin');
    layui.use(['jquery'], function(){
        const $ = layui.jquery;
        // 模拟登录路由拦截
        $(function(){
            let login = JSON.parse(sessionStorage.getItem("login"));
            if(login == 0){
                window.location.href='/sign/in';
                return false;
            }else{
                return false;
            }
        })
    });
</script>
</body>
</html>