<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>后台登录</title>
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
	    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body class="login-bg">
    <div class="login">
        <h1>Welcome!</h1>
        <form method="post" class="layui-form">
            <div class="layui-form-item"> <input name="username" placeholder="用户名" type="text" lay-verify="required" class="layui-input"></div>
            <div class="layui-form-item"> <input name="password" lay-verify="required" placeholder="密码" type="password" class="layui-input"></div>
            <div class="layui-form-item" style="position:relative">
				<div class="layui-row">
					<input name="vercode" lay-verify="required" placeholder="图像验证码" type="text" class="layui-input">
					<div class="captcha">
						<img id="refresh_captcha" src="https://www.oschina.net/action/user/captcha" width="116" height="36" onclick="this.src = this.src +'?'+new Date().getTime()">
					</div>
				</div>
            </div>
			<div class="layui-form-item">
				<input name="otp" lay-verify="required" placeholder="OTP校验码" type="text" class="layui-input">
				<input name="remember" type="checkbox" lay-skin="primary" title="记住密码">
            </div>
			<div class="layui-form-item"><button class="layui-btn w100" lay-submit lay-filter="login" type="submit">登录</button></div>
        </form>
    </div>


    <script src="/static/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript">
        layui.extend({
            admin: '{/}./static/js/admin'
        });
        layui.use(['form', 'jquery'], function () {
            var form = layui.form,
                $ = layui.jquery,
                admin = layui.admin;
            //监听提交
            form.on('submit(login)', function (data) {
                $.ajax({
                    type: "POST",
                    url: 'https://www.easy-mock.com/mock/5bce79baeaf09a28dd3eb6e2/example/_copy_1553766771817',
                    data: data.field,
                    // dataType: "dataType",
                    success: function (res) {
                        if (res.code === 200) {
                            layer.msg(res.msg, {icon: 1, time: 2000}, function () {
                                sessionStorage.setItem("login", 1)
                                location.href = './index.html'
                            });
                        } else {
                            layer.msg(res.msg, {icon: 2});
                            $("#refresh_captcha").trigger()
                        }
                    },
                    error: function (err) {
                        console.log(err);
                        $("#refresh_captcha").trigger();
                        if (err.responseJSON.code) {
                            layer.msg(err.responseJSON.msg, {icon: 2});
                        } else {
                            layer.msg('未知错误', {icon: 5});
                            $("#refresh_captcha").target()
                        }
                    }
                });
                return false;
            });
        });
        layui.use(['jquery'], function () {
            var imgArr = [];
            imgArr[0] = "/static/images/bg1.png";
            // imgArr[1] = "";
            // imgArr[2] = "";
            // imgArr[3] = "";
            // imgArr[4] = "";
            //输出随机的背景图
            var imgIndex = parseInt(Math.random() * (imgArr.length));
            var $ = layui.jquery;
            $("body").css("background", "url('" + imgArr[imgIndex] + "') no-repeat 50% 0").css("background-size", "100%");
        });
    </script>
    <!-- 底部结束 -->
</body>

</html>